@startuml Buckshot Roulette
title Buckshot Roulette
skinparam {
  ClassBackgroundColor White
  ClassBorderColor Black
  FontSize 12
  TitleFontSize 14
  TitleFontStyle bold
}

hide empty members

package "Model Layer" {
    interface Model {
        + Shoot (boolean toDealer) : int
        + gameIsOver() : boolean
        + utilizeObject(SpecialObject) : boolean
        + isPlayerTurn() : boolean
        + distributeObjects() : Pair<List<SpecialObject>, List<SpecialObject>>
    }
  
    class ModelImpl {
        
        + getGameData() : GameState
        - dealer : Partecipant
        - player : Partecipant
        - strategy : AIStrategy
        - shotgun : Shotgun
        - turnManager : TurnManager
    }
  
    ModelImpl ..|> Model : implements



    interface Partecipant {
        + addObjects(List<SpecialObject>) : void
        + useObject(SpecialObject) : boolean
        + shoot(Shotgun s, Partecipant target) : int
        + isDead() : boolean
    }

    abstract class AbstractPartecipant  {
        - objects : List<SpecialObject>
        - lives : LivesManager 
    }

    class TurnManager {
      + endTurn(blank : boolean, selfShot : boolean) : void
      + isPlayerTurn() : boolean
    }
    
    class Dealer {
        
    }
    
    class Player {
        
    }
    
    AbstractPartecipant <|-- Dealer : extends
    AbstractPartecipant <|-- Player : extends
    Partecipant <|.. AbstractPartecipant

    interface SpecialObject {
    + use() : void
    }

    class LivesManager {
        - maxLives : int
        - initialLives : int
        + noLivesRemaining() : boolean
        + smoke() : void
        + IAmHit(int damage) : void
    }

    class Shotgun {
        - bullets : List<Boolean>
        + isEmpty() : boolean
        + recharge() : void
        + isBulletAlive() : boolean
        + shoot() : boolean
        + cut() : void
        + isCutted() : boolean
        + getDamage() : int
        + howManyRemaining() : int
        + skip() : void
    }

    Interface AIStrategy {
        + getObjectsChosen() : List<SpecialObjects>
        + ShootToPlayer() : boolean
    }

    class BasicStrategy {

    }
    
    class GameState {
        - shotgun : ShotgunState
        - objects : list<SpecialObjects>
    }

    class Beer {

    }

    class Cigarette {

    }

    class Saw {

    }

    class Handcuffs {

    }

    class MagnifyingGlass {

    }
}
package "Controller" {
  class Controller {
    - view : GUI
    - model : Model
    + handleInput()
    + updateView()
  }
}  

package "View" {
  class GUI {
    - controller : Controller
    + display()
    + getUserInput()
  }
}

ModelImpl *-- Partecipant : contains 2
SpecialObject *-- AbstractPartecipant : owns multiple
LivesManager *-- AbstractPartecipant
Controller --> Model : controls
GUI --> Controller : uses
Controller --> GUI : updates
Shotgun *--down ModelImpl : contains
AIStrategy *-- ModelImpl : contains
TurnManager *-- ModelImpl : contains
Beer ..|> SpecialObject
Handcuffs ..|> SpecialObject
Cigarette ..|> SpecialObject
MagnifyingGlass ..|> SpecialObject
Saw ..|> SpecialObject
BasicStrategy ..|> AIStrategy

@enduml